source 'http://rubygems.org'

gem 'sinatra'
gem 'require_all'
gem 'rake'
gem 'activerecord', '~> 5.2', :require => 'active_record'
gem 'sqlite3'
gem 'shotgun'
gem 'pry'
gem 'sinatra-activerecord', :require => 'sinatra/activerecord'
gem 'sinatra-contrib'
gem 'bcrypt', '~> 3.1.7'
gem 'rack-flash3'