source 'http://rubygems.org'

gem 'sinatra'
gem 'require_all'
gem 'rake'
gem 'activerecord', '~> 5.2'
gem 'sqlite3'
gem 'shotgun'
gem 'pry'
gem 'sinatra-activerecord'
gem 'sinatra-contrib'
gem 'bcrypt'
gem 'rack-flash3'